[project]
name = "fin-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dspy>=3.1.3",
    "langchain>=1.2.10",
    "langchain-community>=0.4.1",
    "litellm[google]>=1.81.13",
    "yfinance>=1.2.0",
]
